language: python
env:
  - DJANGO_VERSION=1.8.6
  - DJANGO_VERSION=1.9.7
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.1
  - DJANGO_VERSION=3.2
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  exclude: 
    - python: "2.7"
      env: DJANGO_VERSION=2.2
    - python: "2.7"
      env: DJANGO_VERSION=3.0
    - python: "2.7"
      env: DJANGO_VERSION=3.1
    - python: "2.7"
      env: DJANGO_VERSION=3.2

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-erase --cover-package=restosaur tests/
after_success:
  - coveralls

