language: python
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.10
  - DJANGO_VERSION=1.8.6
  - DJANGO_VERSION=1.9.7
  - DJANGO_VERSION=1.10b1
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-erase --cover-package=restosaur
after_success:
  - coveralls

